### ISSUE TITLE
error creating browser on .Net 4.6.2

### ISSUE THREAD

**Issue by cosmaioan** [kblok/puppeteer-sharp#90] opened 2018-03-12 21:09 UTC
Simplest console app (copy paste of code from the working console app working in Core 2)

System.InvalidOperationException: 'No process is associated with this object.'

var chromiumRevision = 526987;

            Console.WriteLine("Downloading chromium");
            await Downloader.CreateDefault().DownloadRevisionAsync(chromiumRevision);

            Console.WriteLine("Navigating google");

            //this line throws an error (stack trace below)
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true
            }, chromiumRevision);

------------------------

{"No process is associated with this object."}

   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_Id()
   at PuppeteerSharp.Launcher.<ForceKillChrome>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PuppeteerSharp.Launcher.<LaunchAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Puppeteer.<LaunchAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PuppeteerSharpPdfDemo.MainClass.<MainAsync>d__1.MoveNext() in C:\temp\data\puppeteer-sharp-master\puppeteer-sharp-master\demos\ConsoleApp1\Program.cs:line 27

**Comment by kblok** [comment] 2018-03-12 23:20
I'm releasing v0.3 in a few days. I believe this will be fixed there.

**Comment by kblok** [comment] 2018-03-14 12:40
Could you try now with version v0.3 @cosmaioan ?

**Comment by cosmaioan** [comment] 2018-03-14 22:14
I tried v0.3 but got 

> Exception: Failed to create connection
> Inner exception: The Process object must have the UseShellExecute property set to false in order to redirect IO streams.
> 

I tried to set this UseShellExecute to false in the source code of puppeter sharp but has side effects that generate other errors.

**Comment by kblok** [comment] 2018-03-15 11:47
Thank you for your feedback @cosmaioan. I was able to reproduce your issue. I was also able to make tests fail. I made the Test project a multitarget project and run the tests against `net472`.

I'll work on this issue and I'll also add a `net471` test on our CI to keep testing this.

Thanks again.

cc @Meir017

**Closed** 2018-03-17 12:52 UTC
Labels: bug

**Comment by kblok** [comment] 2018-03-17 13:24
@cosmaioan I just published 0.3.1. Could you give it a try?

**Comment by jhear1287** [comment] 2018-07-23 12:48
I think the issue is related to Websocket, upon checking code, it uses websocket to connect to chrome. i also notice this is issue when i deploy it to windows server 2008 r2. but when i run it to my local machine which windows 10 there's no issues.

You may also refer to this link.
https://msdn.microsoft.com/en-us/library/hh159285
